config/routes.rb
Rails.application.routes.draw do

	resources :trips do
		collection do
			get :unpaid
			get :personal
			get :business
			get :income
			get :company
		end
		resources :notes
		resources :invoices
		resources :links
	end

	resources :note_categories

	devise_for :users
	# get 'home/index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root to: "home#index"

	# mount ActionCable.server => ‘/cable'
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_many :links
	has_many :invoices, dependent: :destroy
	has_many :notes, dependent: :destroy
	belongs_to :user
	validates_presence_of :name, :start_date, :end_date

	scope :personal, -> { where( is_personal: true ) }
	scope :business, -> { where( is_personal: false ) }
	scope :paid, -> { where( is_paid: true ) }
	scope :unpaid, -> { where( is_paid: false ) }
	scope :ytd, -> { where(start_date: (Time.now.beginning_of_year - 1.day)..Time.now.midnight) }
	# scope :requested_year, -> { where( "start_date > ? AND end_date < ?", params[:year] + "-01-01", params[:year] + "-12-31" ) }
	scope :past, -> { where("start_date <= ?", Time.now ) }
	scope :expenses, -> { where( invoices: {is_income: false} )}
	scope :income, -> { where( invoices: {is_income: true} )}

	self.per_page = 20

	# scope :previous_trip, -> { where(end_date: < end_date ) }

	def previous_trip
	  self.class.where("end_date < ?", end_date).order("end_date DESC").first
	end

	def next_trip
	  self.class.where("end_date > ?", end_date).order("end_date ASC").first
	end

	COMPANY_NAMES = ['Parkview', 'Global Med', '360', 'Air Escort Medical', 'Air Care 1', '']
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	before_action :authenticate_user!

	before_action :set_trip, only: [:show, :edit, :update, :destroy]
	before_action :set_trips_list, only: [:business, :personal, :unpaid]

	# GET /trips
	def index
		@trips = current_user.trips.past.paginate(page: params[:page])
		if !params[:year].blank?
			start_params = params[:year] + "-01-01"
			end_params = params[:year] + "-12-31"

			@trips = current_user.trips.where("start_date > ? AND end_date < ?", start_params, end_params).sort_by(&:start_date).paginate(page: params[:page])
			@trip_category = params[:year].to_s
		end
		@trip_years = @trips.group_by{ |t| t.start_date.beginning_of_year }
		@trip_months = @trips.group_by{ |t| t.start_date.beginning_of_month }
		@trips_this_year = current_user.trips.ytd
	end

	def business
		@trip_category = "Business"
		@trips = Trip.business.paginate(page: params[:page])
		@trip_years = current_user.trips.business.past.group_by{ |t| t.start_date.beginning_of_year }
		@trip_months = current_user.trips.business.past.group_by{ |t| t.start_date.beginning_of_month }
		@trips_this_year = current_user.trips.business.past.ytd

		render action: :index
	end

	def personal
		@trip_category = "Personal"
		@trips = Trip.personal.paginate(page: params[:page])
		@trip_years = current_user.trips.personal.past.group_by{ |t| t.start_date.beginning_of_year }
		@trip_months = current_user.trips.personal.past.group_by{ |t| t.start_date.beginning_of_month }
		@trips_this_year = current_user.trips.personal.past.ytd

		render action: :index
	end

	def unpaid
		@trip_category = "Unpaid"
		@trips = Trip.unpaid.paginate(page: params[:page])
		@trip_years = current_user.trips.business.unpaid.past.group_by{ |t| t.start_date.beginning_of_year }
		@trip_months = current_user.trips.business.unpaid.past.group_by{ |t| t.start_date.beginning_of_month }
		@trips_this_year = current_user.trips.unpaid.past.ytd

		render action: :index
	end

	def income
		if !params[:year].blank?
			@page_title = params[:year].to_s + " Income"
			
			start_params = params[:year] + "-01-01"
			end_params = params[:year] + "-12-31"

			if !params[:company].blank?
				company_name = params[:company]
			else
				company_name = 'Parkview'
			end
			
			# @income_by_company = current_user.trips.joins(:invoices).business.income.where("start_date > ? AND end_date < ?", start_params, end_params).group_by{ |t| t.company_name }.collect(:amount).sum
			@companies_list = current_user.trips.business.where("start_date > ? AND end_date < ?", start_params, end_params).collect(&:company_name).uniq

			@The_Income = current_user.trips.joins(:invoices).business.income.where("start_date >= ? AND end_date <= ? AND company_name = ?", start_params, end_params, company_name).sum(:amount)
			@All_Income = current_user.trips.joins(:invoices).business.income.where("start_date >= ? AND end_date <= ?", start_params, end_params).sum(:amount)
			# select * from trips where company_name = NAME, join invoices, sum amount 
			# @income = Trip.invoices.sum
			# @income_by_company = current_user.trips.joins(:invoices).business.income.where("start_date > ? AND end_date < ?", start_params, end_params).collect(&:company_name).uniq
		else
			@page_title = "YTD Income"
		end
	end

	def sum_amount # this is for the income reporting
		Trip.invoices.sum(:amount)
	end

	def company
		if !params[:year].blank?
			start_params = params[:year] + "-01-01"
			end_params = params[:year] + "-12-31"
		end
		
		@trips = current_user.trips.business.where("start_date > ? AND end_date < ? AND company_name = ?", start_params, end_params, "Global Med").sort_by(&:start_date)#.paginate(page: params[:page])
		@trip_category = params[:year].to_s

		@trip_years = @trips.group_by{ |t| t.start_date.beginning_of_year }
		@trip_months = @trips.group_by{ |t| t.start_date.beginning_of_month }
		@trips_this_year = current_user.trips.ytd

		render action: :index
	end

	# GET /trips/1
	def show
		@note = @trip.notes.build
		@invoice = @trip.invoices.build
		@link = @trip.links.build
		@invoices_amount = @trip.invoices.all.sum{ |e| e.amount }
	end

	# GET /trips/new
	def new
		@trip = current_user.trips.build
	end

	# GET /trips/1/edit
	def edit
	end

	# POST /trips
	def create
		@trip = current_user.trips.build(trip_params)

		if @trip.save
			redirect_to @trip, notice: 'Trip was successfully created.'
		else
			render :new
		end
	end

	# PATCH/PUT /trips/1
	def update
		if @trip.update(trip_params)
			redirect_to @trip, notice: 'Trip was successfully updated.'
		else
			render :edit
		end
	end

	# DELETE /trips/1
	def destroy
		@trip.destroy
		redirect_to trips_url, notice: 'Trip was successfully destroyed.'
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_trip
		@trip = current_user.trips.find(params[:id])
	end

	def set_trips_list
		@trips = current_user.trips.business.past.sort_by(&:start_date)
	end

	# Only allow a trusted parameter "white list" through.
	def trip_params
		params.require(:trip).permit(:name, :company_name, :is_personal, :is_paid, :description, :routing, :tripit_link, :start_date, :end_date)
	end
end

app/helpers/trips_helper.rb
module TripsHelper

	def days_out_by_month(start_date, end_date)
	  distance_of_time_in_words(start_date, end_date)
	end

	def trip_length
	  distance_of_time_in_words(@trip.start_date, ( @trip.end_date + 1.day ))
	end

end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true, class: 'needs-validation', html: {novalidate: true}) do |f| %>

	<% if trip.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

		<ul>
			<% trip.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<!-- <div class="field"> -->
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control', required: true %>
	<div class="invalid-feedback">
		You need to name this thing
	</div>

	<div class="input-group mt-3 mb-3">
		<div class="input-group-prepend">
			<!-- <label class="input-group-text" for="inputGroupSelect01">Options</label> -->
			<%= f.label :company_name, class: 'input-group-text' %>
		</div>
		<%= f.select :company_name, Trip::COMPANY_NAMES, {}, { class: 'custom-select' } %>
	</div>

	<div class="custom-control custom-switch">
		<%= f.check_box :is_personal, class: 'custom-control-input' %>
		<%= f.label :is_personal, class: 'custom-control-label', name: 'Is this a personal trip?' %>
	</div>

	<div class="custom-control custom-switch">
		<%= f.check_box :is_paid, class: 'custom-control-input' %>
		<%= f.label :is_paid, class: 'custom-control-label', name: 'Have you been paid?' %>
	</div>

	<div class="form-row">
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control' %>
	</div>

	<div class="form-row">
		<%= f.label :routing %>
		<%= f.text_field :routing, class: 'form-control', required: true %>
		<div class="invalid-feedback">
			At least tell me the expected route
		</div>
	</div>

	<div class="form-row">
		<%= f.label :tripit_link %>
		<%= f.text_field :tripit_link, class: 'form-control' %>
	</div>

	<div class="form-row">
		<%= f.label :start_date %>
		<%= f.date_select :start_date%>
	</div>

	<div class="form-row">
		<%= f.label :end_date %>
		<%= f.date_select :end_date%>
	</div>

	<div class="actions">
		<%= f.submit class: 'btn btn-primary' %>
		<%= link_to 'Cancel', trips_path, class: 'btn btn-outline-secondary' %>
	</div>
<% end %>

app/views/trips/edit.html.erb
<%# ------------------------------------------------------------------------ begin main content %>

<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

app/views/trips/income.erb
<h3><%= @page_title %></h3>
<p>$<%= @All_Income %> total</p>
<%# @websites.includes(:domains).map{|website| website.domains.sum(:costs)}.sum %>
<%= params[:company] %>: $<%= number_with_delimiter(@The_Income, :delimiter => ',') %>
<hr>
<%= @companies_list.sort.each do |company, trips| %>
	<a href="/trips/income?company=<%= company %>&year=<%= params[:year] %>"><%= company %></a> | 
<%# company.includes(:invoices).map{|company| company.invoice.sum(:amount)}.sum %>
<%# @income_by_company.sort.each do |company, trips| %>
<% end %>

app/views/trips/index.html.erb
<% content_for :sidebar do %>
<h2><%= @trips.count %> trips total</h2>
<!-- <h2><%= @trips_this_year.count %> trips <abbr title="Year to Date">ytd</abbr></h2> -->
<p>
	<a href="http://www.gcmap.com/mapui?P=<% @trips_this_year.each do |trips| %><%= trips.routing + "," %><% end %>&DU=mi&SG=500&SU=mph">YTD trips mapped</a>
</p>

<%= link_to 'Add A Trip', new_trip_path, :class => 'btn btn-outline-primary btn-block' %>
<dl>
	<% @trip_years.sort.reverse.each do |year, trips| %>
	<dd><strong><a href="/trips/<%# @trip_category.downcase %>?year=<%= year.strftime('%Y') %>"><%= year.strftime('%Y') %></a></strong>: <%= trips.size %></dd>
	<% end %>
</dl>
<% end %><!-- end .sidebar -->
<%# ------------------------------------------------------------------------ begin main content %>

<h1 title="are belong to us">All Your <%= @trip_category %> Trips</h1>

<% @trip_months.sort.reverse.each do |month, trips| %>
	<h3><%= month.strftime('%B %Y') %></h3>
	<table class="table table-striped flight-details">
		<thead>
			<tr>
				<th width="300px"></th>
				<th>Start Date</th>
				<th>End Date</th>
				<th width="125px"></th>
			</tr>
		</thead>

		<tbody>
			<%= render partial: "shared/trip", collection: trips, as: :trip %>
		</tbody>
	</table>
<% end -%>
<%# will_paginate @trips %>

app/views/trips/new.html.erb
<%# ------------------------------------------------------------------------ begin main content %>

<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

app/views/trips/show.html.erb
<% title @trip.name + ' | ' + @trip.start_date.strftime('%d %b %Y')  %>

<% content_for :sidebar do %>
	<% if @trip.is_paid %>
		<h3>This invoice is paid</h3>
	<% end -%>
	<%# link_to "Add Image", new_trip_image_path(@trip), class: 'btn btn-primary' %>
	<% if @trip.start_date >= Date.today %>
		<h2>In <%= distance_of_time_in_words(@trip.start_date, ( Date.today )) %>!!</h2>
		<hr>
	<% end %>

	<h2>Links</h2>
	<dl id="link_list">
		<%= render "shared/link" %>
	</dl>

	<%= link_to "New Link", new_trip_link_path(@trip), id: "new_link", class: 'btn btn-mini btn-outline-primary btn-sm' %>
	<hr>

	<% if !@trip.is_personal %>
		<h2>Invoiced Amt</h2>
		<dl id="invoice_list">
		 <%= render "shared/invoice" %>
		</dl>

		<h2>Total Invoice <span class="<%= @trip.is_paid ? 'green' : 'red' %>">$<%= @invoices_amount %></span></h2>
		<h5>Add Invoice</h5>
		<%= render "invoices/form" %>
	<% end %><!-- /if is_personal -->
<% end %>
<%# ------------------------------------------------------------------------ begin main content %>

<h2><%= @trip.name %></h2>
<p class="text-muted">
	<%= @trip.description %>
</p>

<div class="row">
	<div class="col-10">
		<% if !@trip.is_personal %>
			<span class="badge badge-primary"><%= @trip.company_name %></span>
			<% if @trip.is_paid? %>
					<span class="badge badge-success"data-reflex="click->PaidReflex#change" data-id="<%= @trip.id %>" data-is_paid="false">paid</span>
			<% elsif !@trip.is_paid && !@trip.is_personal %>
				<span class="badge badge-danger" data-reflex="click->PaidReflex#change" data-id="<%= @trip.id %>" data-is_paid="true">unpaid</span>
			<% end -%>
		<% end -%>
		<% if @trip.routing? %>
			<%= link_to "http://www.gcmap.com/mapui?P=" + @trip.routing + "&MS=bm&DU=mi&SG=500&SU=kts", class: 'badge badge-secondary' do %>
				<i class="fas fa-plane"></i> Flight Map
			<% end %>
		<% end #end if -%>
		<% if @trip.tripit_link? %>
			<%= link_to "TripIt", @trip.tripit_link, class: 'badge badge-secondary' %>
		<% end %>
	</div>
</div><!-- /row -->

<div class="row justify-content-md-center mb-10">
	<ul class="pager list-inline">
		<% if @trip.previous_trip %>
			<li class="previous list-inline-item"><%= link_to @trip.previous_trip do %><i class="fas fa-arrow-left"></i> <% end %>
			</li>
		<% end %>

		<h3 class="text-info"><%= @trip.start_date.strftime('%d %b %Y') %></h3>
		<span class="text-muted elevated-baseline"> - <%= trip_length %> - </span>
		<h3 class="text-info"><%= @trip.end_date.strftime('%d %b %Y') %></h3>

		<% if @trip.next_trip %>
			<li class="next list-inline-item"><%= link_to @trip.next_trip, title: 'Next' do %> <i class="fas fa-arrow-right"></i><% end %></li>
		<% else %>
			<li class="next disabled list-inline-item">-></li>
		<% end %>
	</ul>
</div><!-- /row -->

<div class="row">
	<div class="col-4 btn-group btn-group-sm">
		<%= link_to edit_trip_path(@trip), class: 'btn btn-outline-secondary' do %><i class="far fa-edit"></i><% end %>
		<%= link_to trips_path, class: 'btn btn-outline-dark' do %><i class="fas fa-th-list"></i><% end %>
		<%= link_to trip_path(@trip), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' do %><i class="far fa-trash-alt"></i><% end %>
	</div>
</div>

<hr>

<div class="row">
	<h2 class="col-12">Notes:</h2>
	<div class="notes col-12">
		<%= render 'shared/note' %>
		<%= render 'notes/form' %>
	</div><!-- /notes -->
</div>