config/routes.rb
Rails.application.routes.draw do

	resources :trips do
		collection do
			get :unpaid
			get :personal
			get :business
			get :income
			get :company
		end
		resources :notes
		resources :invoices
		resources :links
	end

	resources :note_categories

	devise_for :users
	# get 'home/index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root to: "home#index"

	# mount ActionCable.server => ‘/cable'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :note_category
  belongs_to :trip

  validates_presence_of :content#, :note_category_id
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :authenticate_user!

	before_action :set_trip
	before_action :set_note, only: [:show, :edit, :update, :destroy]

	# GET trips/1/notes/1
	def show
	end

	# GET trips/1/notes/new
	def new
		@note = @trip.notes.build
	end

	# GET trips/1/notes/1/edit
	def edit
	end

	# POST trips/1/notes
	def create
		@note = @trip.notes.build(note_params)

		if @note.save
			redirect_to(@note.trip)
		else
			render action: 'new'
		end
	end

	# PUT trips/1/notes/1
	def update
		if @note.update_attributes(note_params)
			redirect_to([@note.trip], notice: 'Note was successfully updated.')
		else
			render action: 'edit'
		end
	end

	# DELETE trips/1/notes/1
	def destroy
		@note.destroy

		redirect_to trip_notes_url(@trip)
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_trip
		@trip = Trip.find(params[:trip_id])
	end

	def set_note
		@note = @trip.notes.find(params[:id])
	end

	# Only allow a trusted parameter "white list" through.
	def note_params
		params.require(:note).permit( :content, :note_category_id )
	end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="new_note row">
	<div class="comment-metadata col-3">
		<span>New note as: <%= current_user.email %></span>
	</div><!-- /comment-metadata col-3 -->
<!-- /note_header insert -->

	<div class="col-6">

		<%= form_for([@note.trip, @note], class: 'needs-validation', html: {novalidate: true}) do |f| %>
			<% if @note.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

				<ul>
					<% @note.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div class="form-group">
				<%= f.text_area :content, placeholder: 'Well.. say something', class: 'form-control', rows: '6', required: true %>
				<div class="invalid-feedback">
					You&rsquo;ve got to say something
				</div>
			</div>

			<div class="input-group mb-3">
				<div class="input-group-prepend">
					<!-- <label class="input-group-text" for="inputGroupSelect01">Options</label> -->
					<%= f.label :category, class: 'input-group-text' %>
				</div>
				<%= f.collection_select :note_category_id, NoteCategory.all, :id, :name, {}, { class: 'custom-select' } %>
			</div>

			<div class="actions">
				<%= f.submit class: 'btn btn-primary btn-sm' %>
			</div>
		<% end %>
	</div><!-- /col-6 -->
</div><!-- /new_note -->

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%# link_to 'Show', [@note.trip, @note] %> |
<%= link_to 'Back', trips_path(@note.trip) %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Category</th>
    <th>Trip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trip.notes.each do |note| %>
  <tr>
    <td><%= note.content %></td>
    <td><%= note.category %></td>
    <td><%= note.trip %></td>
    <td><%= link_to 'Show', [note.trip, note] %></td>
    <td><%= link_to 'Edit', edit_trip_note_path(note.trip, note) %></td>
    <td><%= link_to 'Destroy', [note.trip, note], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_trip_note_path(params[:trip_id]) %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Cancel', trip_path(@note.trip) %>

app/views/notes/show.html.erb
<p>
  <b>Content:</b>
  <%= @note.content %>
</p>

<p>
  <b>Category:</b>
  <%= @note.category %>
</p>

<p>
  <b>Trip:</b>
  <%= @note.trip %>
</p>


<%= link_to 'Edit', edit_trip_note_path(@note.trip, @note) %> |
<%= link_to 'Back', trip_notes_path(@note.trip) %>