config/routes.rb
Rails.application.routes.draw do

	resources :trips do
		collection do
			get :unpaid
			get :personal
			get :business
			get :income
			get :company
		end
		resources :notes
		resources :invoices
		resources :links
	end

	resources :note_categories

	devise_for :users
	# get 'home/index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root to: "home#index"

	# mount ActionCable.server => ‘/cable'
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">&copy; James</span>
  </div>
</footer>

app/views/shared/_income.erb
$<%= trip.invoices.sum{ |e| e.amount.to_i } %> 

app/views/shared/_invoice.html.erb
<% @trip.invoices.each do |invoice| %>
	<% if invoice.persisted? %>

	<dd id="invoice_<%= invoice.id %>">
		<span>$<%= invoice.amount %>
			<% if invoice.is_income? %>Income<% else %>Expense<% end %>

		 - <%= link_to "X", [invoice.trip, invoice], method: :delete, data: { confirm: 'Are you sure?' } %>
		</span>
	</dd>
	<% end -%>
<% end -%>

app/views/shared/_link.html.erb
<% @trip.links.each do |link| %>
	<% if link.persisted? %>
		<dd id="link_<%= link.id %>">
			<%= link_to link.title, link.url %>
			<span class="pull-right">
				<%= link_to edit_trip_link_path(link.trip, link) do %><i class="far fa-edit grey small"></i><% end %>
				<%= link_to [link.trip, link], method: :delete, data: { confirm: 'Are you sure?' } do %><i class="far fa-trash-alt red small"></i><% end -%>
			</span>
		</dd>
	<% end -%>
<% end -%>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "danger" : "success" %>" role="alert">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<a class="navbar-brand" href="#">TN-6</a>
	<% if user_signed_in? %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/trips">Trips</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filtered Trips</a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
						<%= link_to "Business Trips", business_trips_path, class: 'dropdown-item' %>
						<%= link_to "Personal Trips", personal_trips_path, class: 'dropdown-item' %>
						<%= link_to "Unpaid Trips", unpaid_trips_path, class: 'dropdown-item' %>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Other Stuff</a>
					<div class="dropdown-menu" aria-labelledby="dropdown02">
						<%= link_to "New Trip", new_trip_url, class: 'dropdown-item' %>
						<%= link_to "Note Categories", note_categories_url, class: 'dropdown-item' %>
						<%= link_to "New Note Category", new_note_category_url, class: 'dropdown-item' %>
						<%= link_to "Income Reports ", income_trips_path(company: 'Parkview', year: last_year), class: 'dropdown-item' %>
					</div>
				</li>
			</ul>
	<!--
			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
	 -->
				<ul class="navbar-nav">
					<li class="nav-item"><a class="nav-link">Salve, <%= current_user.email %></a></li>
					<li class="nav-item"><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
					</li>
				</ul>
		</div>
	<% end -%> <!-- end of signed-in menu -->
	</nav>
</header>

app/views/shared/_note.html.erb
<% @trip.notes.each do |note| %>
	<% if note.persisted? %>
	<div class="row" id="note_<%= note.id %>">
		<%= render "shared/note_header", note: note %>
			<div class="col-6">
				<div class="note_content">
					<div class="">
						<%= markdown(note.content) %>
					</div><!-- / -->
					<div class="actions well well-small">
						<div class="btn-group">
							<%= link_to edit_trip_note_path(note.trip, note), class: 'btn btn-sm btn-outline-secondary' do %><i class="far fa-edit"></i><% end %>
							<%= link_to trip_note_path(note.trip, note), method: :delete, confirm: 'Are you sure?', class: 'btn btn-sm btn-outline-danger' do %><i class="far fa-trash-alt"></i><% end %>
						</div><!-- /btn-gro -->
					</div><!-- /well -->
				</div><!-- /note_content -->
			</div><!-- /col-6 -->
		</div><!-- /row -->
	<% end -%>
<% end -%>

app/views/shared/_note_header.html.erb
<div class="comment-metadata col-3">

	<h3><%= note.note_category.name %></h3>
	<%= note.trip.user.email %>

	<% if params[:controller] == 'trips' %>
		<%= link_to trip_path(note.trip, view: "notes", anchor: "note_#{note.id}") do %>
			<i class="fas fa-link"></i>
		<% end %>
		<div class="text-muted when-posted"><%= time_ago_in_words note.created_at %> ago</div>
		<div class="posted-on">
			<div>
				<%= note.created_at.strftime("%d %b %Y") %>
			</div>
		</div>
	<% end -%>
</div><!-- /comment-metadata col-3 -->

app/views/shared/_trip.html.erb
<tr>
	<td width="200px">
			<%= link_to trip.name, trip_path(trip) %>
		<% if !trip.is_personal -%>
			<% if !trip.is_paid -%>
				<span class="badge badge-danger" data-reflex="click->PaidReflex#change" data-id="<%= trip.id %>" data-is_paid="true">unpaid</span>
				<h3><i class="glyphicon glyphicon-remove" aria-hidden="true"></i> $<%= trip.invoices.all.sum{ |e| e.amount.to_i } %> Outstanding</h3>
			<% elsif trip.is_paid? && trip.start_date < Time.now %>
				<span class="badge badge-success"data-reflex="click->PaidReflex#change" data-id="<%= trip.id %>" data-is_paid="false">paid</span>
			<% end -%>
			<br>
			<% if !trip.company_name.blank? -%>
				<span class="text-muted"> &mdash; <%= trip.company_name %></span>
			<% end -%>
		<% end -%>
	</td>
	<td><span class="badge badge-secondary"><%= trip.start_date.strftime('%d %b %Y') %></span></td>
	<td><span class="badge badge-secondary"><%= trip.end_date.strftime('%d %b %Y') %></span></td>
	<td width="100px">
		<div class="btn-group btn-group-sm" role="group" aria-label="...">
			<%= link_to trip_path(trip), class: 'btn btn-outline-primary' do %><i class="far fa-eye"></i><% end %>
			<%= link_to edit_trip_path(trip), class: 'btn btn-outline-secondary' do %><i class="far fa-edit"></i><% end %>
		</div>
	</td>
</tr>
<tr class="text-muted">
	<td>
		<% if trip.start_date > Date.today  %>
			<%= pluralize(days_until(trip.start_date), "day") %> until this trip!
		<% else %>
		<span class="text-muted"><%= trip.description %></span>
		<% end %>
	</td>
	<td><%= distance_of_time_in_words(trip.start_date, trip.end_date + 1.day) %></td>
	<td><%= trip.routing %></td>
	<td>
		<% if !trip.notes.empty? %>
			<%= trip.notes.size %> <i class="far fa-comment"></i>
		<% end %>
		<% if !trip.links.empty? %>
			<%= trip.links.size %> <i class="fas fa-link"></i>
		<% end %>
		<%# if !trip.images.empty? %>
		<%# trip.images.size %> <i class="Xfar Xfa-images"></i>
		<%# end %>
	</td>
</tr>