config/routes.rb
Rails.application.routes.draw do

	resources :trips do
		collection do
			get :unpaid
			get :personal
			get :business
			get :income
			get :company
		end
		resources :notes
		resources :invoices
		resources :links
	end

	resources :note_categories

	devise_for :users
	# get 'home/index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root to: "home#index"

	# mount ActionCable.server => ‘/cable'
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :trip

  validates_presence_of :title, :url
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :set_trip
	before_action :set_link, only: [:edit, :update, :destroy]

	# GET trips/1/links
	def index
		@links = @trip.links
	end

	# GET trips/1/links/new
	def new
		@link = @trip.links.build
	end

	# GET trips/1/links/1/edit
	def edit
	end

	# POST trips/1/links
	def create
		@link = @trip.links.build(link_params)

		if @link.save
			redirect_to(@trip, notice: 'Link was successfully created.')
		else
			render action: 'new'
		end
	end

	# PUT trips/1/links/1
	def update
		if @link.update_attributes(link_params)
			redirect_to([@trip], notice: 'Link was successfully updated.')
		else
			render action: 'edit'
		end
	end

	# DELETE trips/1/links/1
	def destroy
		@link.destroy

		redirect_to trip_url(@trip)
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_trip
		@trip = Trip.find(params[:trip_id])
	end

	def set_link
		@link = @trip.links.find(params[:id])
	end

	# Only allow a trusted parameter "white list" through.
	def link_params
		params.require(:link).permit(:title, :url)
	end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for([@link.trip, @link]) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', [@link.trip, @link] %> |
<%= link_to 'Back', trip_links_path(@link.trip) %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.title %></td>
    <td><%= link.url %></td>
    <td><%= link_to 'Show', [link.trip, link] %></td>
    <td><%= link_to 'Edit', edit_trip_link_path(link.trip, link) %></td>
    <td><%= link_to 'Destroy', [link.trip, link], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_trip_link_path(params[:trip_id]) %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Cancel', trip_path(@link.trip) %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @link.title %>
</p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>


<%= link_to 'Edit', edit_trip_link_path(@link.trip, @link) %> |
<%= link_to 'Back', trip_links_path(@link.trip) %>